// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DB_First_Using_EFCore_Power_Tool.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DB_First_Using_EFCore_Power_Tool.Data.Contexts
{
    public partial interface INorthwindDbContextProcedures
    {
        Task<List<EmployeeSalesbyCountryResult>> EmployeeSalesbyCountryAsync(DateTime? beginning_Date, DateTime? ending_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> NewProductDeleteCommandAsync(int? original_ProductID, string original_ProductName, int? isNull_SupplierID, int? original_SupplierID, int? isNull_CategoryID, int? original_CategoryID, int? isNull_QuantityPerUnit, string original_QuantityPerUnit, int? isNull_UnitPrice, decimal? original_UnitPrice, int? isNull_UnitsInStock, short? original_UnitsInStock, int? isNull_UnitsOnOrder, short? original_UnitsOnOrder, int? isNull_ReorderLevel, short? original_ReorderLevel, bool? original_Discontinued, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
