// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DB_First_Using_EFCore_Power_Tool.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DB_First_Using_EFCore_Power_Tool.Data.Contexts
{
    public partial class NorthwindDbContext
    {
        private INorthwindDbContextProcedures _procedures;

        public virtual INorthwindDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new NorthwindDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public INorthwindDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class NorthwindDbContextProcedures : INorthwindDbContextProcedures
    {
        private readonly NorthwindDbContext _context;

        public NorthwindDbContextProcedures(NorthwindDbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<EmployeeSalesbyCountryResult>> EmployeeSalesbyCountryAsync(DateTime? beginning_Date, DateTime? ending_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Beginning_Date",
                    Value = beginning_Date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "Ending_Date",
                    Value = ending_Date ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<EmployeeSalesbyCountryResult>("EXEC @returnValue = [dbo].[Employee Sales by Country] @Beginning_Date = @Beginning_Date, @Ending_Date = @Ending_Date", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> NewProductDeleteCommandAsync(int? original_ProductID, string original_ProductName, int? isNull_SupplierID, int? original_SupplierID, int? isNull_CategoryID, int? original_CategoryID, int? isNull_QuantityPerUnit, string original_QuantityPerUnit, int? isNull_UnitPrice, decimal? original_UnitPrice, int? isNull_UnitsInStock, short? original_UnitsInStock, int? isNull_UnitsOnOrder, short? original_UnitsOnOrder, int? isNull_ReorderLevel, short? original_ReorderLevel, bool? original_Discontinued, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Original_ProductID",
                    Value = original_ProductID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_ProductName",
                    Size = 80,
                    Value = original_ProductName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_SupplierID",
                    Value = isNull_SupplierID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_SupplierID",
                    Value = original_SupplierID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_CategoryID",
                    Value = isNull_CategoryID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_CategoryID",
                    Value = original_CategoryID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_QuantityPerUnit",
                    Value = isNull_QuantityPerUnit ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_QuantityPerUnit",
                    Size = 40,
                    Value = original_QuantityPerUnit ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_UnitPrice",
                    Value = isNull_UnitPrice ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_UnitPrice",
                    Precision = 19,
                    Scale = 4,
                    Value = original_UnitPrice ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Money,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_UnitsInStock",
                    Value = isNull_UnitsInStock ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_UnitsInStock",
                    Value = original_UnitsInStock ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_UnitsOnOrder",
                    Value = isNull_UnitsOnOrder ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_UnitsOnOrder",
                    Value = original_UnitsOnOrder ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "IsNull_ReorderLevel",
                    Value = isNull_ReorderLevel ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Original_ReorderLevel",
                    Value = original_ReorderLevel ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.SmallInt,
                },
                new SqlParameter
                {
                    ParameterName = "Original_Discontinued",
                    Value = original_Discontinued ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[NewProductDeleteCommand] @Original_ProductID = @Original_ProductID, @Original_ProductName = @Original_ProductName, @IsNull_SupplierID = @IsNull_SupplierID, @Original_SupplierID = @Original_SupplierID, @IsNull_CategoryID = @IsNull_CategoryID, @Original_CategoryID = @Original_CategoryID, @IsNull_QuantityPerUnit = @IsNull_QuantityPerUnit, @Original_QuantityPerUnit = @Original_QuantityPerUnit, @IsNull_UnitPrice = @IsNull_UnitPrice, @Original_UnitPrice = @Original_UnitPrice, @IsNull_UnitsInStock = @IsNull_UnitsInStock, @Original_UnitsInStock = @Original_UnitsInStock, @IsNull_UnitsOnOrder = @IsNull_UnitsOnOrder, @Original_UnitsOnOrder = @Original_UnitsOnOrder, @IsNull_ReorderLevel = @IsNull_ReorderLevel, @Original_ReorderLevel = @Original_ReorderLevel, @Original_Discontinued = @Original_Discontinued", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
